image:
  repository: ghcr.io/youssefachraf/training-platform-frontend
  tag: ""
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 8080

route:
  host: ""
  tlsTermination: edge

securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

env:
  BACKEND_UPSTREAM: ""
  CHATBOT_UPSTREAM: ""
