n8n:
  image:
    tag: "sha-e0609d5"
  env:
    N8N_WEBHOOK_URL: ""
    N8N_OWNER_EMAIL: "admin@localhost.local"
  persistence:
    storageClassName: ""

redis:
  persistence:
    storageClassName: ""

metricsExporter:
  enabled: true
  image:
    tag: "sha-9f51c78"

vault:
  enabled: false
