apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/part-of: training-platform
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.n8n.persistence.storageClassName }}
  storageClassName: {{ .Values.n8n.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.n8n.persistence.size }}
