apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.service.name }}
  labels:
    app.kubernetes.io/name: chatbot-redis
    app.kubernetes.io/part-of: training-platform
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: chatbot-redis
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
