image:
  tag: "sha-138daf3"

route:
  host: "training-platform.apps-crc.testing"

env:
  BACKEND_UPSTREAM: "http://backend.training-platform.svc.cluster.local:4000"
  CHATBOT_UPSTREAM: "http://n8n.training-platform.svc.cluster.local:5678"
