kube-prometheus-stack:
  prometheus-node-exporter:
    securityContext:
      fsGroup: 1000680000
      runAsGroup: 1000680000
      runAsUser: 1000680000

  kube-state-metrics:
    securityContext:
      fsGroup: 1000680000
      runAsGroup: 1000680000
      runAsUser: 1000680000

  prometheusOperator:
    securityContext:
      fsGroup: 1000680000
      runAsGroup: 1000680000
      runAsUser: 1000680000

  prometheus:
    prometheusSpec:
      securityContext:
        fsGroup: 1000680000
        runAsGroup: 1000680000
        runAsUser: 1000680000

  alertmanager:
    alertmanagerSpec:
      securityContext:
        fsGroup: 1000680000
        runAsGroup: 1000680000
        runAsUser: 1000680000

  grafana:
    securityContext:
      runAsUser: 1000680000
      runAsGroup: 1000680000
      fsGroup: 1000680000
    initChownData:
      enabled: false
