apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: training-platform-overnight
  namespace: training-platform
spec:
  weekdays: "1-5"
  sleepAt: "20:00"
  wakeUpAt: "08:00"
  timeZone: "Europe/Paris"
  suspendStatefulSets: true
