{{- if .Values.route.host }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: training-platform
  {{- if or .Values.route.balance .Values.route.disableCookies }}
  annotations:
    {{- with .Values.route.balance }}
    haproxy.router.openshift.io/balance: {{ . | quote }}
    {{- end }}
    {{- if .Values.route.disableCookies }}
    haproxy.router.openshift.io/disable_cookies: "true"
    {{- end }}
  {{- end }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: frontend
  port:
    targetPort: http
  tls:
    termination: {{ .Values.route.tlsTermination }}
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
