apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-attachments
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: training-platform
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.attachments.persistence.storageClassName }}
  storageClassName: {{ .Values.attachments.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.attachments.persistence.size }}
