apiVersion: v1
kind: Service
metadata:
  name: backend-redis
  labels:
    app.kubernetes.io/name: backend-redis
    app.kubernetes.io/part-of: training-platform
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: backend-redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
