apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/YoussefAchraf/training-platform-gitops.git
    targetRevision: main
    path: charts/chatbot
    helm:
      valueFiles:
        - ../../environments/local-okd/chatbot-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: training-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
