apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YoussefAchraf/training-platform-gitops.git
    targetRevision: main
    path: charts/kube-green
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-green
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: kube-green-manager-role
      jsonPointers:
        - /rules
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: sleepinfos.kube-green.com
      jsonPointers:
        - /spec/conversion
        - /status
