apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-green-sleepinfo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/YoussefAchraf/training-platform-gitops.git
    targetRevision: main
    path: charts/kube-green-sleepinfo
  destination:
    server: https://kubernetes.default.svc
    namespace: training-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
