image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 5432

securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  size: 5Gi
  storageClassName: ""

postgresDb: training_platform
postgresUser: postgres

existingSecret: postgres-credentials

vault:
  enabled: false
  role: postgres-role
  secretPath: training-platform/data/postgres
