apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-init-secret
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: training-platform
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["vault-init-keys"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-init-secret
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: training-platform
subjects:
  - kind: ServiceAccount
    name: {{ .Values.vault.server.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: vault-init-secret
  apiGroup: rbac.authorization.k8s.io
