{{- if .Values.injectorRestart.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-injector-restart
  labels:
    app.kubernetes.io/name: vault-injector-restart
    app.kubernetes.io/part-of: training-platform
{{- end }}
