name: On main merge

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  verify:
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  dast:
    uses: ./.github/workflows/dast.yml
    secrets: inherit
